# Generated by Django 4.2.7 on 2023-11-28 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, verbose_name='Название объявления')),
                ('description', models.CharField(max_length=127, verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='avatars', verbose_name='Фото вещи')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, unique=True, verbose_name='Название категории')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.IntegerField(blank=True, null=True, verbose_name='Денежное вознаграждение')),
                ('comment', models.CharField(blank=True, max_length=127, null=True, verbose_name='Комментарий к заявке')),
                ('accepted', models.BooleanField(default=False, verbose_name='Принята автором объявления')),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.advert', verbose_name='Объявление')),
            ],
        ),
    ]
