# Generated by Django 4.2.7 on 2024-01-14 16:43

from django.db import migrations

def combine_names(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    User = apps.get_model("authentication", "User")
    for user in User.objects.all():
        user.name = "%s %s" % (user.first_name, user.last_name)
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
    ]
