# Generated by Django 4.2.7 on 2024-01-16 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='category',
        ),
        migrations.CreateModel(
            name='AdvertCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основная категория')),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advert_categories', to='api.advert', verbose_name='Объявление')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category', verbose_name='Категория вещи')),
            ],
            options={
                'verbose_name': 'Категория объявления',
                'verbose_name_plural': 'Категории объявлений',
            },
        ),
        migrations.AddField(
            model_name='advert',
            name='category',
            field=models.ManyToManyField(related_name='adverts', through='api.AdvertCategory', to='api.category', verbose_name='Категории'),
        ),
    ]
