# Generated by Django 4.2.7 on 2024-01-17 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_advert_category_advertcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='category',
            new_name='categories',
        ),
        migrations.AlterUniqueTogether(
            name='advertcategory',
            unique_together={('advert', 'category', 'is_main')},
        ),
    ]
