# Generated by Django 4.2.7 on 2024-01-18 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_category_advert_categories_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='advertcategory',
            unique_together={('advert', 'is_main')},
        ),
    ]
