# Generated by Django 4.2.7 on 2024-01-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_advertcategory_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
    ]
