version: '3.5'
services:
  web:
    build:
      context: .
      dockerfile: advert/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./advert:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    env_file:
      - "doc_2023.env"
    environment:
      POSTGRES_DB: dbAdvert
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root